name: Beetle Adventure Rac (North America)
sha1: e5ab4d226c08d22f68a2edcc48870203e67454b8
options:
  basename: beetleadventurerac
  target_path: beetle.z64
  elf_path: build/beetleadventurerac.elf
  base_path: .
  platform: n64
  compiler: IDO

  # asm_path: asm
  # src_path: src
  # build_path: build
  # create_asm_dependencies: True

  ld_script_path: beetleadventurerac.ld
  ld_dependencies: True

  find_file_boundaries: True
  header_encoding: ASCII

  o_as_suffix: True
  use_legacy_include_asm: False
  mips_abi_float_regs: o32

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  # section_order: [".text", ".data", ".rodata", ".bss"]
  # auto_link_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path:
    - symbol_addrs.txt
  reloc_addrs_path:
    - reloc_addrs.txt

  # undefined_funcs_auto_path: undefined_funcs_auto.txt
  # undefined_syms_auto_path: undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  # string_encoding: ASCII
  # data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
  # libultra_symbols: True
  # hardware_regs: True
  # gfx_ucode: # one of [f3d, f3db, f3dex, f3dexb, f3dex2]
segments:
  - name: header
    type: header
    start: 0x0

  - name: boot
    type: bin
    start: 0x40

  - name: entry
    type: code
    start: 0x1000
    vram: 0x80000400
    subsegments:
      - [0x1000, hasm]

  - name: main
    type: code
    start: 0x1050
    vram: 0x80000450
    follows_vram: entry
    bss_size: 0x10BA0
    subsegments:
      - [0x1050, asm]
      - [0x1A930, data]
      - { type: bss, vram: 0x80022BD0 }

  - type: bin
    start: 0x237D0
    follows_vram: main

  - [0x1000000]
